version: '3.8'

services: 
    main:
      build: 
        context: .
        dockerfile: Dockerfile
      command: 'php artisan serve --host=0.0.0.0'
      working_dir: /app
      volumes:
        - ./:/app
      ports:
        - 8000:8000
      # depends_on: 
      #   - project-db
      # networks:
      #   - app-network

    # queue:
    #     build: 
    #         context: .
    #         dockerfile: Dockerfile
    #     command: 'php artisan queue:work'
    #     depends_on: 
    #         - db        

    project-db:
      platform: linux/x86_64
      image: mysql:8.0
      environment: 
        MYSQL_DATABASE: main
        MYSQL_USER: admin
        MYSQL_ROOT: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - myapp:/home/node/app
      ports:
        - 8889:3306
      # networks:
      #   - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  myapp: